# Generated by Django 5.2.13 on 2026-04-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(blank=True, help_text='Module that generated the notification (e.g., finance, crm)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20),
        ),
    ]
