# Generated by Django 5.0.14 on 2026-04-13 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_company_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo / Produção'), ('stored', 'Estocado'), ('retired', 'Aposentado'), ('broken', 'Quebrado / Manutenção'), ('ordered', 'Em Compra')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='JSON payload with CI specific specs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_kind', models.CharField(choices=[('runs_on', 'Roda em'), ('depends_on', 'Depende de'), ('member_of', 'Membro de'), ('manages', 'Gerencia'), ('installed_on', 'Instalado em')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='cmdb.ci')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='cmdb.ci')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True)),
                ('criticality_level', models.IntegerField(default=1, help_text='Impact severity (1-5)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ci',
            name='ci_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cis', to='cmdb.citype'),
        ),
    ]
