# Generated by Django 5.2.13 on 2026-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='Regra de recorrência (ex: FREQ=MONTHLY;INTERVAL=1)', max_length=255, null=True),
        ),
    ]
