# Generated by Django 5.0.14 on 2026-02-03 13:40

import shared_kernel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media_library/%Y/%m/', validators=[shared_kernel.validators.validate_chat_file]),
        ),
    ]
