# Generated by Django 5.0.14 on 2026-02-27 18:43

import shared_kernel.utils
import shared_kernel.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=shared_kernel.utils.TenantUploadTo('media_library'), validators=[shared_kernel.validators.validate_chat_file]),
        ),
    ]
