# Generated by Django 5.0.14 on 2026-04-13 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('crm', '0016_fix_default_legacy_column_semantics'),
        ('messenger', '0020_rename_messenger_c_user_id_d4ed4f_idx_messenger_c_user_id_58f83d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_response_minutes', models.PositiveIntegerField(help_text='Tempo alvo para primeira resposta em minutos')),
                ('target_resolution_minutes', models.PositiveIntegerField(help_text='Tempo alvo para resolução em minutos')),
                ('business_hours_only', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
            },
        ),
        migrations.RenameIndex(
            model_name='dealattachment',
            new_name='crm_dealatt_company_7a52a2_idx',
            old_name='crm_dealatt_company_0e98a3_idx',
        ),
        migrations.RenameIndex(
            model_name='dealattachment',
            new_name='crm_dealatt_company_60115d_idx',
            old_name='crm_dealatt_company_2f7d7e_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationinboundevent',
            new_name='crm_integra_company_6aa270_idx',
            old_name='crm_integra_company_9f79a0_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationinboundevent',
            new_name='crm_integra_company_4a0559_idx',
            old_name='crm_integra_company_164314_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationinboundevent',
            new_name='crm_integra_company_9621a1_idx',
            old_name='crm_integra_company_8c0cff_idx',
        ),
        migrations.AddField(
            model_name='deal',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='record_type',
            field=models.CharField(choices=[('incident', 'Incidente'), ('service_request', 'Requisição de Serviço'), ('problem', 'Problema'), ('change', 'Mudança'), ('opportunity', 'Oportunidade')], default='incident', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='sla_resolution_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='sla_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='sla_status',
            field=models.CharField(choices=[('within', 'Dentro do prazo'), ('at_risk', 'Em risco'), ('breached', 'Violado')], default='within', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='column_kind',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('planned', 'Planejada'), ('active', 'Em andamento'), ('done', 'Concluída'), ('custom', 'Customizada'), ('discover', 'Descoberta'), ('design', 'Design'), ('acquire', 'Aquisição'), ('build', 'Construção'), ('transition', 'Transição'), ('operate', 'Operação'), ('deliver', 'Entrega'), ('support', 'Suporte')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealactivity',
            name='activity_type',
            field=models.CharField(choices=[('column_change', 'Mudança de Coluna'), ('stage_change', 'Mudança de Coluna (Legado)'), ('note', 'Nota Manual'), ('automation', 'Automação'), ('creation', 'Criação'), ('ai_action', 'Ação de IA'), ('ai_suggestion', 'Sugestão de IA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='integrationinboundevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.slapolicy'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'record_type'], name='crm_deal_company_911903_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'sla_status'], name='crm_deal_company_65c0e1_idx'),
        ),
    ]
