# Generated by Django 5.0.14 on 2026-04-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_slapolicy_and_more'),
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='service_catalog.serviceitem'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Crítica / Urgente')], default='MEDIUM', max_length=10),
        ),
    ]
