# Generated by Django 5.0.14 on 2026-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
        ('crm', '0018_deal_service_item_alter_deal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='affected_cis',
            field=models.ManyToManyField(blank=True, related_name='deals', to='cmdb.ci'),
        ),
    ]
