# Generated by Django 5.0.14 on 2026-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_deal_affected_cis'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='backout_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='change_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='implementation_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='test_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
