# Generated by Django 5.0.14 on 2026-04-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_deal_backout_plan_deal_change_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_known_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
