# Generated by Django 5.0.14 on 2026-04-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_deal_is_known_error_deal_resolution_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='value_stream_phase',
            field=models.CharField(choices=[('demand', 'Demanda'), ('product_design', 'Design de Produto'), ('creation', 'Criação / Desenvolvimento'), ('onboarding', 'Onboarding / Entrega'), ('realization', 'Realização de Valor')], default='demand', max_length=30),
        ),
        migrations.AddField(
            model_name='deal',
            name='xla_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Average XLA score (1-10)', max_digits=3, null=True),
        ),
    ]
