# Generated by Django 5.0.14 on 2026-04-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('crm', '0022_column_value_stream_phase_deal_xla_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='XLAFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1-10')),
                ('comment', models.TextField(blank=True, null=True)),
                ('ease_of_use', models.IntegerField(default=5)),
                ('speed_satisfaction', models.IntegerField(default=5)),
                ('outcome_satisfaction', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xla_feedbacks', to='crm.contact')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xla_feedbacks', to='crm.deal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
