# Generated by Django 5.0.14 on 2026-04-13 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_soft_delete'),
        ('crm', '0023_xlafeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('api_url', models.URLField(help_text='URL base da Evolution API')),
                ('api_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('default_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.column')),
                ('default_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
