# Generated by Django 5.0.14 on 2026-04-17 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_updated_at'),
        ('crm', '0026_deal_ai_metadata'),
        ('messenger', '0021_contactblock_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.conversation')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swarm', to='crm.deal')),
                ('participants', models.ManyToManyField(related_name='swarms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swarm Session',
                'verbose_name_plural': 'Swarm Sessions',
            },
        ),
    ]
