# Generated by Django 5.0.14 on 2026-04-22 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_updated_at'),
        ('crm', '0027_swarm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='cab_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='cab_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='change_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='change_type',
            field=models.CharField(choices=[('standard', 'Padrão (Baixo Risco)'), ('normal', 'Normal (Requer CAB)'), ('emergency', 'Emergencial (Urgente)')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='workaround',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CSIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identificado'), ('evaluating', 'Em Avaliação'), ('planned', 'Planejado'), ('in_progress', 'Em Execução'), ('completed', 'Concluído'), ('rejected', 'Rejeitado')], default='identified', max_length=20)),
                ('proposed_solution', models.TextField(blank=True, null=True)),
                ('expected_outcome', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csi_entries', to='crm.deal')),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csi_entries', to='crm.pipeline')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_csi', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_csi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSI Entry',
                'verbose_name_plural': 'CSI Register',
                'ordering': ['-created_at'],
            },
        ),
    ]
