# Generated by Django 5.0.14 on 2026-04-22 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_updated_at'),
        ('crm', '0028_deal_cab_approval_deal_cab_date_deal_change_impact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('avg_lead_time_days', models.FloatField(default=0.0)),
                ('throughput_weekly', models.IntegerField(default=0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('avg_xla_score', models.FloatField(default=0.0)),
                ('active_deals_count', models.IntegerField(default=0)),
                ('bottleneck_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Metric Snapshot',
                'verbose_name_plural': 'Metric History',
                'ordering': ['-date'],
                'unique_together': {('date', 'pipeline', 'company')},
            },
        ),
    ]
